// rates.js - Delivery Pincode Rates for Daily Deals With Crazy Offers
// Base rates are BEFORE 18% GST. GST is added at checkout.
// Usage: window.DeliveryRates.check(pincode) => { available, zone, base_rate, charge, days, area }

window.DeliveryRates = (function () {

  // Zone definitions: each zone has a base delivery charge (before GST)
  const ZONES = {
    LOCAL: { label: "Local", base: 30, days: "1-2 Business Days" },
    CITY: { label: "Within City", base: 40, days: "2-3 Business Days" },
    STATE: { label: "Within State", base: 50, days: "3-4 Business Days" },
    METRO: { label: "Metro City", base: 60, days: "3-5 Business Days" },
    STANDARD: { label: "Standard", base: 70, days: "5-7 Business Days" },
    REMOTE: { label: "Remote Area", base: 100, days: "7-10 Business Days" },
  };

  const GST_RATE = 0.18;

  // Pincode database: pincode prefix (first 3-6 digits) mapped to zone and area name
  // Gujarat (Local / State)
  const PINCODE_DB = {
    // Rajkot local
    "360001": { zone: "LOCAL", area: "Rajkot - City Centre" },
    "360002": { zone: "LOCAL", area: "Rajkot - Bhaktinagar" },
    "360003": { zone: "LOCAL", area: "Rajkot - Kalavad Road" },
    "360004": { zone: "LOCAL", area: "Rajkot - University Road" },
    "360005": { zone: "LOCAL", area: "Rajkot - Gondal Road" },
    "360006": { zone: "LOCAL", area: "Rajkot - Mavdi" },
    "360007": { zone: "LOCAL", area: "Rajkot - Kothariya" },
    "360020": { zone: "LOCAL", area: "Rajkot - Aji Dam" },
    "360021": { zone: "LOCAL", area: "Rajkot - Metoda" },
    "360022": { zone: "LOCAL", area: "Rajkot - Shapar" },
    "360023": { zone: "LOCAL", area: "Rajkot - Veraval (Shapar)" },
    "360024": { zone: "LOCAL", area: "Rajkot - Hadala" },
    "360025": { zone: "LOCAL", area: "Rajkot - Virpur" },
    "360026": { zone: "LOCAL", area: "Rajkot - Paddhari" },
    "360035": { zone: "LOCAL", area: "Rajkot - Vinchhiya" },
    "360040": { zone: "LOCAL", area: "Rajkot - Jasdan" },
    "360050": { zone: "LOCAL", area: "Rajkot - Gondal" },
    "360060": { zone: "LOCAL", area: "Rajkot - Jetpur" },
    "360070": { zone: "LOCAL", area: "Rajkot - Dhoraji" },
    "360075": { zone: "LOCAL", area: "Rajkot - Upleta" },
    "360080": { zone: "LOCAL", area: "Rajkot - Jamkandorna" },
    "360085": { zone: "LOCAL", area: "Rajkot - Vankaner" },
    // Surat
    "395001": { zone: "CITY", area: "Surat - City Centre" },
    "395002": { zone: "CITY", area: "Surat - Adajan" },
    "395003": { zone: "CITY", area: "Surat - Ring Road" },
    "395004": { zone: "CITY", area: "Surat - Katargam" },
    "395005": { zone: "CITY", area: "Surat - Udhna" },
    "395006": { zone: "CITY", area: "Surat - Varachha" },
    "395007": { zone: "CITY", area: "Surat - Piplod" },
    "395009": { zone: "CITY", area: "Surat - Bhestan" },
    "395010": { zone: "CITY", area: "Surat - Sachin" },
    // Ahmedabad
    "380001": { zone: "CITY", area: "Ahmedabad - Old City" },
    "380002": { zone: "CITY", area: "Ahmedabad - Kankaria" },
    "380004": { zone: "CITY", area: "Ahmedabad - Ellisbridge" },
    "380005": { zone: "CITY", area: "Ahmedabad - Paldi" },
    "380006": { zone: "CITY", area: "Ahmedabad - Navrangpura" },
    "380007": { zone: "CITY", area: "Ahmedabad - Shahibaug" },
    "380008": { zone: "CITY", area: "Ahmedabad - Sabarmati" },
    "380009": { zone: "CITY", area: "Ahmedabad - Gomtipur" },
    "380013": { zone: "CITY", area: "Ahmedabad - Maninagar" },
    "380015": { zone: "CITY", area: "Ahmedabad - New Wadaj" },
    "380016": { zone: "CITY", area: "Ahmedabad - Ghatlodia" },
    "380019": { zone: "CITY", area: "Ahmedabad - Jodhpur" },
    "380021": { zone: "CITY", area: "Ahmedabad - Vejalpur" },
    "380051": { zone: "CITY", area: "Ahmedabad - Naranpura" },
    "380052": { zone: "CITY", area: "Ahmedabad - Satellite" },
    "380054": { zone: "CITY", area: "Ahmedabad - Prahlad Nagar" },
    "380055": { zone: "CITY", area: "Ahmedabad - Bodakdev" },
    "380058": { zone: "CITY", area: "Ahmedabad - Vastrapur" },
    "380059": { zone: "CITY", area: "Ahmedabad - Thaltej" },
    "380060": { zone: "CITY", area: "Ahmedabad - Bopal" },
    "380061": { zone: "CITY", area: "Ahmedabad - SG Highway" },
    // Vadodara
    "390001": { zone: "CITY", area: "Vadodara - Sayajigunj" },
    "390002": { zone: "CITY", area: "Vadodara - Alkapuri" },
    "390003": { zone: "CITY", area: "Vadodara - Fatehgunj" },
    "390004": { zone: "CITY", area: "Vadodara - Gotri Road" },
    "390005": { zone: "CITY", area: "Vadodara - Waghodia Road" },
    "390006": { zone: "CITY", area: "Vadodara - Karelibaug" },
    "390007": { zone: "CITY", area: "Vadodara - Akota" },
    "390008": { zone: "CITY", area: "Vadodara - Nizampura" },
    "390009": { zone: "CITY", area: "Vadodara - Subhanpura" },
    "390010": { zone: "CITY", area: "Vadodara - Sama" },
    "390012": { zone: "CITY", area: "Vadodara - Vasna" },
    "390015": { zone: "CITY", area: "Vadodara - New Sama" },
    "390019": { zone: "CITY", area: "Vadodara - Harni" },
    "390020": { zone: "CITY", area: "Vadodara - Makarpura" },
    "390023": { zone: "CITY", area: "Vadodara - Manjalpur" },
    // Other Gujarat cities
    "364001": { zone: "STATE", area: "Bhavnagar - City" },
    "364002": { zone: "STATE", area: "Bhavnagar - Ghogha Circle" },
    "362001": { zone: "STATE", area: "Junagadh - City" },
    "362011": { zone: "STATE", area: "Junagadh - Sardar Baug" },
    "370001": { zone: "STATE", area: "Bhuj - City" },
    "370020": { zone: "STATE", area: "Bhuj - Mirzapar" },
    "396001": { zone: "STATE", area: "Navsari - City" },
    "396191": { zone: "STATE", area: "Valsad - City" },
    "388001": { zone: "STATE", area: "Anand - City" },
    "387001": { zone: "STATE", area: "Nadiad - City" },
    "384001": { zone: "STATE", area: "Mehsana - City" },
    "382001": { zone: "STATE", area: "Gandhinagar - City" },
    "382010": { zone: "STATE", area: "Gandhinagar - Sector 10" },
    "382021": { zone: "STATE", area: "Gandhinagar - Sector 21" },
    "394601": { zone: "STATE", area: "Vyara - City" },
    "394150": { zone: "STATE", area: "Bardoli - City" },
    "394305": { zone: "STATE", area: "Surat Rural" },
    "385001": { zone: "STATE", area: "Palanpur - City" },
    "363001": { zone: "STATE", area: "Surendranagar - City" },
    "361001": { zone: "STATE", area: "Jamnagar - City" },
    "361002": { zone: "STATE", area: "Jamnagar - Bedi Bandar" },
    "361003": { zone: "STATE", area: "Jamnagar - Digvijay Plot" },
    "361005": { zone: "STATE", area: "Jamnagar - Shantinagar" },
    "361008": { zone: "STATE", area: "Jamnagar - Navinchandra Marg" },
    "360575": { zone: "STATE", area: "Amreli - City" },
    // Metro Cities
    "400001": { zone: "METRO", area: "Mumbai - Fort" },
    "400002": { zone: "METRO", area: "Mumbai - Mandvi" },
    "400003": { zone: "METRO", area: "Mumbai - Masjid Bunder" },
    "400004": { zone: "METRO", area: "Mumbai - Girgaon" },
    "400005": { zone: "METRO", area: "Mumbai - Colaba" },
    "400006": { zone: "METRO", area: "Mumbai - Malabar Hill" },
    "400007": { zone: "METRO", area: "Mumbai - Grant Road" },
    "400008": { zone: "METRO", area: "Mumbai - Mumbai Central" },
    "400009": { zone: "METRO", area: "Mumbai - Mazgaon" },
    "400010": { zone: "METRO", area: "Mumbai - Byculla" },
    "400011": { zone: "METRO", area: "Mumbai - Parel" },
    "400012": { zone: "METRO", area: "Mumbai - Dadar" },
    "400013": { zone: "METRO", area: "Mumbai - Sion" },
    "400014": { zone: "METRO", area: "Mumbai - Wadala" },
    "400015": { zone: "METRO", area: "Mumbai - Matunga" },
    "400016": { zone: "METRO", area: "Mumbai - Mahim" },
    "400017": { zone: "METRO", area: "Mumbai - Dharavi" },
    "400018": { zone: "METRO", area: "Mumbai - Worli" },
    "400019": { zone: "METRO", area: "Mumbai - Prabhadevi" },
    "400020": { zone: "METRO", area: "Mumbai - Churchgate" },
    "400025": { zone: "METRO", area: "Mumbai - Khar" },
    "400050": { zone: "METRO", area: "Mumbai - Bandra West" },
    "400051": { zone: "METRO", area: "Mumbai - Bandra East" },
    "400053": { zone: "METRO", area: "Mumbai - Santacruz" },
    "400054": { zone: "METRO", area: "Mumbai - Vile Parle" },
    "400055": { zone: "METRO", area: "Mumbai - Andheri West" },
    "400059": { zone: "METRO", area: "Mumbai - Andheri East" },
    "400063": { zone: "METRO", area: "Mumbai - Borivali West" },
    "400064": { zone: "METRO", area: "Mumbai - Borivali East" },
    "400068": { zone: "METRO", area: "Mumbai - Kandivali" },
    "400069": { zone: "METRO", area: "Mumbai - Malad" },
    "400070": { zone: "METRO", area: "Mumbai - Goregaon" },
    "400072": { zone: "METRO", area: "Mumbai - Jogeshwari" },
    "400076": { zone: "METRO", area: "Mumbai - Powai" },
    "400078": { zone: "METRO", area: "Mumbai - Ghatkopar" },
    "400081": { zone: "METRO", area: "Mumbai - Mulund" },
    "400083": { zone: "METRO", area: "Mumbai - Bhandup" },
    "400086": { zone: "METRO", area: "Mumbai - Vikhroli" },
    "400088": { zone: "METRO", area: "Mumbai - Kanjurmarg" },
    "400093": { zone: "METRO", area: "Mumbai - Dombivli East" },
    "400601": { zone: "METRO", area: "Thane - City" },
    "400602": { zone: "METRO", area: "Thane - Naupada" },
    "400615": { zone: "METRO", area: "Navi Mumbai - Vashi" },
    "400614": { zone: "METRO", area: "Navi Mumbai - Nerul" },
    "400706": { zone: "METRO", area: "Navi Mumbai - Airoli" },
    // Delhi NCR
    "110001": { zone: "METRO", area: "New Delhi - Connaught Place" },
    "110005": { zone: "METRO", area: "Delhi - Paharganj" },
    "110006": { zone: "METRO", area: "Delhi - Daryaganj" },
    "110007": { zone: "METRO", area: "Delhi - Old Delhi" },
    "110008": { zone: "METRO", area: "Delhi - Patel Nagar" },
    "110009": { zone: "METRO", area: "Delhi - Shahdara" },
    "110010": { zone: "METRO", area: "Delhi - Tilak Nagar" },
    "110011": { zone: "METRO", area: "Delhi - Karol Bagh" },
    "110012": { zone: "METRO", area: "Delhi - Inderpuri" },
    "110013": { zone: "METRO", area: "Delhi - Kalkaji" },
    "110014": { zone: "METRO", area: "Delhi - Lajpat Nagar" },
    "110015": { zone: "METRO", area: "Delhi - West Patel Nagar" },
    "110016": { zone: "METRO", area: "Delhi - New Friends Colony" },
    "110017": { zone: "METRO", area: "Delhi - Saket" },
    "110018": { zone: "METRO", area: "Delhi - Janakpuri" },
    "110019": { zone: "METRO", area: "Delhi - Govindpuri" },
    "110020": { zone: "METRO", area: "Delhi - Ambedkar Nagar" },
    "110021": { zone: "METRO", area: "Delhi - Mehrauli" },
    "110022": { zone: "METRO", area: "Delhi - Dhaula Kuan" },
    "110023": { zone: "METRO", area: "Delhi - Munirka" },
    "110024": { zone: "METRO", area: "Delhi - Lodi Colony" },
    "110025": { zone: "METRO", area: "Delhi - Okhla" },
    "110028": { zone: "METRO", area: "Delhi - South Extension" },
    "110030": { zone: "METRO", area: "Delhi - Vasant Vihar" },
    "110034": { zone: "METRO", area: "Delhi - Pitampura" },
    "110035": { zone: "METRO", area: "Delhi - Rohini" },
    "110040": { zone: "METRO", area: "Delhi - Narela" },
    "110044": { zone: "METRO", area: "Delhi - Badarpur" },
    "110045": { zone: "METRO", area: "Delhi - Dwarka" },
    "110048": { zone: "METRO", area: "Delhi - Golf Links" },
    "110051": { zone: "METRO", area: "Delhi - Vivek Vihar" },
    "110052": { zone: "METRO", area: "Delhi - Model Town" },
    "110053": { zone: "METRO", area: "Delhi - Shalimar Bagh" },
    "110054": { zone: "METRO", area: "Delhi - Civil Lines" },
    "110055": { zone: "METRO", area: "Delhi - Karawal Nagar" },
    "110058": { zone: "METRO", area: "Delhi - Uttam Nagar" },
    "110059": { zone: "METRO", area: "Delhi - Vikaspuri" },
    "110060": { zone: "METRO", area: "Delhi - Rajouri Garden" },
    "110063": { zone: "METRO", area: "Delhi - Hari Nagar" },
    "110064": { zone: "METRO", area: "Delhi - Tilak Vihar" },
    "110065": { zone: "METRO", area: "Delhi - Sarai Rohilla" },
    "110085": { zone: "METRO", area: "Delhi - Mangolpuri" },
    "110086": { zone: "METRO", area: "Delhi - Sultanpuri" },
    "110088": { zone: "METRO", area: "Delhi - Paschim Vihar" },
    "110091": { zone: "METRO", area: "Delhi - Kondli" },
    "110092": { zone: "METRO", area: "Delhi - Laxmi Nagar" },
    "110093": { zone: "METRO", area: "Delhi - Nandnagri" },
    "110095": { zone: "METRO", area: "Delhi - Dilshad Garden" },
    "110096": { zone: "METRO", area: "Delhi - Yamuna Vihar" },
    "122001": { zone: "METRO", area: "Gurugram - Sector 14" },
    "122002": { zone: "METRO", area: "Gurugram - Sector 40" },
    "122003": { zone: "METRO", area: "Gurugram - DLF Phase 1" },
    "122004": { zone: "METRO", area: "Gurugram - Golf Course Road" },
    "122007": { zone: "METRO", area: "Gurugram - Sohna Road" },
    "122009": { zone: "METRO", area: "Gurugram - Udyog Vihar" },
    "122010": { zone: "METRO", area: "Gurugram - Sector 82" },
    "201301": { zone: "METRO", area: "Noida - Sector 18" },
    "201304": { zone: "METRO", area: "Noida - Sector 62" },
    "201307": { zone: "METRO", area: "Noida - Sector 137" },
    "201309": { zone: "METRO", area: "Noida - Sector 168" },
    "201310": { zone: "METRO", area: "Noida - Sector 63" },
    // Bengaluru
    "560001": { zone: "METRO", area: "Bengaluru - MG Road" },
    "560002": { zone: "METRO", area: "Bengaluru - Shivajinagar" },
    "560003": { zone: "METRO", area: "Bengaluru - Rajajinagar" },
    "560004": { zone: "METRO", area: "Bengaluru - Malleshwaram" },
    "560008": { zone: "METRO", area: "Bengaluru - Sadashivanagar" },
    "560010": { zone: "METRO", area: "Bengaluru - Indiranagar" },
    "560011": { zone: "METRO", area: "Bengaluru - Koramangala" },
    "560016": { zone: "METRO", area: "Bengaluru - Basavanagudi" },
    "560017": { zone: "METRO", area: "Bengaluru - Jayanagar" },
    "560020": { zone: "METRO", area: "Bengaluru - Banashankari" },
    "560025": { zone: "METRO", area: "Bengaluru - Vijayanagar" },
    "560027": { zone: "METRO", area: "Bengaluru - BTM Layout" },
    "560029": { zone: "METRO", area: "Bengaluru - Yeshwanthpur" },
    "560034": { zone: "METRO", area: "Bengaluru - JP Nagar" },
    "560037": { zone: "METRO", area: "Bengaluru - Marathahalli" },
    "560038": { zone: "METRO", area: "Bengaluru - Whitefield" },
    "560041": { zone: "METRO", area: "Bengaluru - HSR Layout" },
    "560043": { zone: "METRO", area: "Bengaluru - Bommanahalli" },
    "560048": { zone: "METRO", area: "Bengaluru - Sarjapur Road" },
    "560066": { zone: "METRO", area: "Bengaluru - Hebbal" },
    "560068": { zone: "METRO", area: "Bengaluru - Electronic City" },
    "560076": { zone: "METRO", area: "Bengaluru - Thanisandra" },
    "560077": { zone: "METRO", area: "Bengaluru - Hennur" },
    "560078": { zone: "METRO", area: "Bengaluru - Nagawara" },
    "560094": { zone: "METRO", area: "Bengaluru - Yelahanka" },
    "560102": { zone: "METRO", area: "Bengaluru - KR Puram" },
    "560103": { zone: "METRO", area: "Bengaluru - Mahadevapura" },
    // Chennai
    "600001": { zone: "METRO", area: "Chennai - George Town" },
    "600002": { zone: "METRO", area: "Chennai - Egmore" },
    "600003": { zone: "METRO", area: "Chennai - Vepery" },
    "600004": { zone: "METRO", area: "Chennai - Chetpet" },
    "600005": { zone: "METRO", area: "Chennai - Kilpauk" },
    "600006": { zone: "METRO", area: "Chennai - T Nagar" },
    "600010": { zone: "METRO", area: "Chennai - Nungambakkam" },
    "600014": { zone: "METRO", area: "Chennai - Kodambakkam" },
    "600015": { zone: "METRO", area: "Chennai - Mylapore" },
    "600017": { zone: "METRO", area: "Chennai - Adyar" },
    "600018": { zone: "METRO", area: "Chennai - West Mambalam" },
    "600019": { zone: "METRO", area: "Chennai - Velachery" },
    "600020": { zone: "METRO", area: "Chennai - Saidapet" },
    "600024": { zone: "METRO", area: "Chennai - Vadapalani" },
    "600028": { zone: "METRO", area: "Chennai - Ashok Nagar" },
    "600040": { zone: "METRO", area: "Chennai - Virugambakkam" },
    "600041": { zone: "METRO", area: "Chennai - Porur" },
    "600042": { zone: "METRO", area: "Chennai - Valasaravakkam" },
    "600053": { zone: "METRO", area: "Chennai - Anna Nagar" },
    "600058": { zone: "METRO", area: "Chennai - Kolathur" },
    "600061": { zone: "METRO", area: "Chennai - Besant Nagar" },
    "600073": { zone: "METRO", area: "Chennai - Pallikaranai" },
    "600091": { zone: "METRO", area: "Chennai - Perambur" },
    "600093": { zone: "METRO", area: "Chennai - Tondiarpet" },
    "600096": { zone: "METRO", area: "Chennai - Sholinganallur" },
    "600100": { zone: "METRO", area: "Chennai - Thoraipakkam" },
    // Kolkata
    "700001": { zone: "METRO", area: "Kolkata - BBD Bagh" },
    "700005": { zone: "METRO", area: "Kolkata - Bhowanipore" },
    "700006": { zone: "METRO", area: "Kolkata - Park Street" },
    "700007": { zone: "METRO", area: "Kolkata - Chowringhee" },
    "700009": { zone: "METRO", area: "Kolkata - Shyambazar" },
    "700013": { zone: "METRO", area: "Kolkata - Sealdah" },
    "700014": { zone: "METRO", area: "Kolkata - Santoshpur" },
    "700017": { zone: "METRO", area: "Kolkata - Alipore" },
    "700019": { zone: "METRO", area: "Kolkata - Ballygunge" },
    "700020": { zone: "METRO", area: "Kolkata - Dhakuria" },
    "700026": { zone: "METRO", area: "Kolkata - Lake Town" },
    "700029": { zone: "METRO", area: "Kolkata - Jadavpur" },
    "700031": { zone: "METRO", area: "Kolkata - Behala" },
    "700032": { zone: "METRO", area: "Kolkata - Barisha" },
    "700033": { zone: "METRO", area: "Kolkata - Sarsuna" },
    "700034": { zone: "METRO", area: "Kolkata - Dum Dum" },
    "700035": { zone: "METRO", area: "Kolkata - Barasat" },
    "700046": { zone: "METRO", area: "Kolkata - Salt Lake" },
    "700050": { zone: "METRO", area: "Kolkata - New Alipore" },
    "700052": { zone: "METRO", area: "Kolkata - Kasba" },
    "700059": { zone: "METRO", area: "Kolkata - Tollygunge" },
    "700064": { zone: "METRO", area: "Kolkata - Garia" },
    "700075": { zone: "METRO", area: "Kolkata - Rajarhat" },
    "700091": { zone: "METRO", area: "Kolkata - New Town" },
    // Hyderabad
    "500001": { zone: "METRO", area: "Hyderabad - Abids" },
    "500002": { zone: "METRO", area: "Hyderabad - Nampally" },
    "500003": { zone: "METRO", area: "Hyderabad - Koti" },
    "500004": { zone: "METRO", area: "Hyderabad - Hyderabad City" },
    "500007": { zone: "METRO", area: "Hyderabad - Secunderabad" },
    "500008": { zone: "METRO", area: "Hyderabad - Musheerabad" },
    "500009": { zone: "METRO", area: "Hyderabad - Malkajgiri" },
    "500016": { zone: "METRO", area: "Hyderabad - Humayun Nagar" },
    "500018": { zone: "METRO", area: "Hyderabad - Jubilee Hills" },
    "500019": { zone: "METRO", area: "Hyderabad - Banjara Hills" },
    "500020": { zone: "METRO", area: "Hyderabad - Somajiguda" },
    "500026": { zone: "METRO", area: "Hyderabad - Saidabad" },
    "500027": { zone: "METRO", area: "Hyderabad - Lakdikapul" },
    "500028": { zone: "METRO", area: "Hyderabad - Mehdipatnam" },
    "500029": { zone: "METRO", area: "Hyderabad - Tolichowki" },
    "500033": { zone: "METRO", area: "Hyderabad - Lingampally" },
    "500034": { zone: "METRO", area: "Hyderabad - Madhapur" },
    "500035": { zone: "METRO", area: "Hyderabad - HITEC City" },
    "500038": { zone: "METRO", area: "Hyderabad - Ameerpet" },
    "500040": { zone: "METRO", area: "Hyderabad - Miyapur" },
    "500045": { zone: "METRO", area: "Hyderabad - Kondapur" },
    "500049": { zone: "METRO", area: "Hyderabad - Kukatpally" },
    "500050": { zone: "METRO", area: "Hyderabad - Bachupally" },
    "500072": { zone: "METRO", area: "Hyderabad - Chanda Nagar" },
    "500081": { zone: "METRO", area: "Hyderabad - Uppal" },
    "500082": { zone: "METRO", area: "Hyderabad - L B Nagar" },
    "500084": { zone: "METRO", area: "Hyderabad - Dilsukhnagar" },
    "500085": { zone: "METRO", area: "Hyderabad - Kothapet" },
    "500086": { zone: "METRO", area: "Hyderabad - Nagole" },
    "500090": { zone: "METRO", area: "Hyderabad - Manikonda" },
    "500096": { zone: "METRO", area: "Hyderabad - Gachibowli" },
    "500097": { zone: "METRO", area: "Hyderabad - Financial District" },
    // Pune
    "411001": { zone: "METRO", area: "Pune - Shivajinagar" },
    "411002": { zone: "METRO", area: "Pune - Camp" },
    "411003": { zone: "METRO", area: "Pune - Kothrud" },
    "411004": { zone: "METRO", area: "Pune - Deccan" },
    "411005": { zone: "METRO", area: "Pune - Parvati" },
    "411006": { zone: "METRO", area: "Pune - Bibwewadi" },
    "411007": { zone: "METRO", area: "Pune - Hadapsar" },
    "411009": { zone: "METRO", area: "Pune - Karve Road" },
    "411011": { zone: "METRO", area: "Pune - Bavdhan" },
    "411014": { zone: "METRO", area: "Pune - Warje" },
    "411015": { zone: "METRO", area: "Pune - Dhayari" },
    "411016": { zone: "METRO", area: "Pune - Kondhwa" },
    "411017": { zone: "METRO", area: "Pune - Wanowrie" },
    "411018": { zone: "METRO", area: "Pune - Undri" },
    "411021": { zone: "METRO", area: "Pune - Baner" },
    "411027": { zone: "METRO", area: "Pune - Wakad" },
    "411028": { zone: "METRO", area: "Pune - Pimple Saudagar" },
    "411033": { zone: "METRO", area: "Pune - Chinchwad" },
    "411037": { zone: "METRO", area: "Pune - Pimpri" },
    "411038": { zone: "METRO", area: "Pune - Akurdi" },
    "411041": { zone: "METRO", area: "Pune - Sangvi" },
    "411045": { zone: "METRO", area: "Pune - Kalyani Nagar" },
    "411046": { zone: "METRO", area: "Pune - Viman Nagar" },
    "411048": { zone: "METRO", area: "Pune - Nagar Road" },
    "411057": { zone: "METRO", area: "Pune - Hinjewadi" },
    "411058": { zone: "METRO", area: "Pune - Kharadi" },
    "411062": { zone: "METRO", area: "Pune - Magarpatta" },
    // Other Standard cities (prefix-based)
    // Jaipur
    "302001": { zone: "STANDARD", area: "Jaipur - City Centre" },
    "302006": { zone: "STANDARD", area: "Jaipur - Malviya Nagar" },
    "302017": { zone: "STANDARD", area: "Jaipur - Vaishali Nagar" },
    "302021": { zone: "STANDARD", area: "Jaipur - Mansarovar" },
    // Lucknow
    "226001": { zone: "STANDARD", area: "Lucknow - Hazratganj" },
    "226010": { zone: "STANDARD", area: "Lucknow - Gomti Nagar" },
    "226016": { zone: "STANDARD", area: "Lucknow - Alambagh" },
    // Chandigarh
    "160001": { zone: "STANDARD", area: "Chandigarh - Sector 17" },
    "160017": { zone: "STANDARD", area: "Chandigarh - Sector 34" },
    "160047": { zone: "STANDARD", area: "Chandigarh - Sector 47" },
    // Bhopal
    "462001": { zone: "STANDARD", area: "Bhopal - MP Nagar" },
    "462003": { zone: "STANDARD", area: "Bhopal - Arera Colony" },
    "462011": { zone: "STANDARD", area: "Bhopal - Kolar" },
    // Indore
    "452001": { zone: "STANDARD", area: "Indore - City Centre" },
    "452010": { zone: "STANDARD", area: "Indore - Vijay Nagar" },
    "452016": { zone: "STANDARD", area: "Indore - Scheme 78" },
    // Nagpur
    "440001": { zone: "STANDARD", area: "Nagpur - City Centre" },
    "440010": { zone: "STANDARD", area: "Nagpur - Dharampeth" },
    "440022": { zone: "STANDARD", area: "Nagpur - Sadar" },
    // Coimbatore
    "641001": { zone: "STANDARD", area: "Coimbatore - City" },
    "641006": { zone: "STANDARD", area: "Coimbatore - RS Puram" },
    "641018": { zone: "STANDARD", area: "Coimbatore - Gandhipuram" },
    // Kochi
    "682001": { zone: "STANDARD", area: "Kochi - Fort Kochi" },
    "682011": { zone: "STANDARD", area: "Kochi - Ernakulam" },
    "682020": { zone: "STANDARD", area: "Kochi - Edapally" },
    // Thiruvananthapuram
    "695001": { zone: "STANDARD", area: "Thiruvananthapuram - City" },
    "695011": { zone: "STANDARD", area: "Thiruvananthapuram - Pattom" },
    // Remote areas - J&K, NE states, Andaman etc.
    "193401": { zone: "REMOTE", area: "Leh - Ladakh" },
    "192001": { zone: "REMOTE", area: "Srinagar - J&K" },
    "190001": { zone: "REMOTE", area: "Srinagar - Jammu" },
    "180001": { zone: "REMOTE", area: "Jammu - City" },
    "737101": { zone: "REMOTE", area: "Gangtok - Sikkim" },
    "793001": { zone: "REMOTE", area: "Shillong - Meghalaya" },
    "781001": { zone: "REMOTE", area: "Guwahati - Assam" },
    "791001": { zone: "REMOTE", area: "Itanagar - Arunachal Pradesh" },
    "795001": { zone: "REMOTE", area: "Imphal - Manipur" },
    "796001": { zone: "REMOTE", area: "Aizawl - Mizoram" },
    "744101": { zone: "REMOTE", area: "Port Blair - Andaman" },
    "605001": { zone: "REMOTE", area: "Pondicherry - City" },
  };

  // Prefix-based fallback lookup (3-digit state codes)
  const PREFIX_ZONES = {
    "360": "LOCAL", "361": "STATE", "362": "STATE", "363": "STATE",
    "364": "STATE", "365": "STATE", "366": "STATE", "367": "STATE",
    "368": "STATE", "369": "STATE", "370": "STATE", "371": "STATE",
    "372": "STATE", "373": "STATE", "374": "STATE", "375": "STATE",
    "376": "STATE", "377": "STATE", "378": "STATE", "379": "STATE",
    "380": "CITY",  "381": "CITY",  "382": "CITY",  "383": "CITY",
    "384": "CITY",  "385": "CITY",  "386": "CITY",  "387": "CITY",
    "388": "CITY",  "389": "CITY",  "390": "CITY",  "391": "CITY",
    "392": "CITY",  "393": "CITY",  "394": "CITY",  "395": "CITY",
    "396": "CITY",  "110": "METRO", "111": "METRO", "122": "METRO",
    "201": "METRO", "400": "METRO", "401": "METRO", "410": "METRO",
    "411": "METRO", "500": "METRO", "560": "METRO", "600": "METRO",
    "700": "METRO", "110": "METRO", "560": "METRO",
    "302": "STANDARD", "226": "STANDARD", "160": "STANDARD",
    "462": "STANDARD", "452": "STANDARD", "440": "STANDARD",
    "641": "STANDARD", "682": "STANDARD", "695": "STANDARD",
    "180": "STANDARD", "781": "STANDARD",
    "737": "REMOTE",   "793": "REMOTE",   "791": "REMOTE",
    "795": "REMOTE",   "796": "REMOTE",   "744": "REMOTE",
    "192": "REMOTE",   "193": "REMOTE",
  };

  function check(pincode) {
    const pin = String(pincode).trim();
    if (!/^\d{6}$/.test(pin)) {
      return { available: false, reason: "Invalid pincode format. Please enter a 6-digit pincode." };
    }

    let zone = null;
    let area = null;

    // Exact match
    if (PINCODE_DB[pin]) {
      zone = PINCODE_DB[pin].zone;
      area = PINCODE_DB[pin].area;
    } else {
      // Prefix fallback (3 digits)
      const prefix3 = pin.substring(0, 3);
      if (PREFIX_ZONES[prefix3]) {
        zone = PREFIX_ZONES[prefix3];
        area = "Your Area";
      }
    }

    if (!zone) {
      return {
        available: false,
        reason: "Delivery not available to this pincode yet. Please contact us on WhatsApp for special delivery arrangements.",
      };
    }

    const zoneInfo = ZONES[zone];
    const baseCharge = zoneInfo.base;
    const gstAmount = Math.round(baseCharge * GST_RATE);
    const totalCharge = baseCharge + gstAmount;

    return {
      available: true,
      zone: zone,
      zone_label: zoneInfo.label,
      area: area,
      base_rate: baseCharge,
      gst: gstAmount,
      charge: totalCharge,
      days: zoneInfo.days,
    };
  }

  return { check, ZONES };
})();
